export { default as LoadingNews } from './LoadingNews'
export { default as News } from './News'
export { default as FeaturedNews } from './FeaturedNews'
export { default as Tab } from './Tab'
export { default as NewsComponent } from './NewsComponent'