export { default as LoadingNews } from './LoadingNews'
export { default as News } from './News'
export { default as FeaturedNews } from './FeaturedNews'
export { default as Categories } from './Categories'
export { default as NewsComponent } from './NewsComponent'